<?php
/**
 * @file
 */

/**
 * Implements hook_views_api().
 */
function uuid_helper_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'uuid_helper'),
  );
}

/**
 * Implements hook_ctools_plugin_directory()
 */
function uuid_helper_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/ctools/' . $plugin_type;
  }
}

/**
 * Implements hook_permission().
 */
function uuid_helper_permission() {
  return array(
    'uuid visible entity edit' => array(
      'title' => 'Display UUID in entity edit',
      'description' => "Display the UUID of an entity in the entity's primary edit form, e.g. node edit.",
    ),
  );
}

/**
 * Implements hook_form_node_form_alter().
 */
function uuid_helper_form_node_form_alter(&$form, $form_state) {
  if (!empty($form_state['node']->uuid) && user_access('uuid visible entity edit')) {
    $form['title']['#field_suffix'] = t('<small>UUID: @uuid</small>', array('@uuid' => $form_state['node']->uuid));
  }
}

/**
 * Implements hook_form_taxonomy_form_term_alter().
 */
function uuid_helper_form_taxonomy_form_term_alter(&$form, $form_state) {
  if (!empty($form_state['term']->uuid) && user_access('uuid visible entity edit')) {
    $form['name']['#field_suffix'] = t('<small>UUID: @uuid</small>', array('@uuid' => $form_state['term']->uuid));
  }
}
